=== Sage-BR/L2JBr/dist/game/data/scripts/ai/areas/ImperialTomb/FourSepulchers/FourSepulchers.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="spawn" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:int" name="sepulcherId" use="optional"/>
								<xs:attribute type="xs:int" name="wave" use="optional"/>
								<xs:attribute type="xs:int" name="npcId" use="optional"/>
								<xs:attribute type="xs:int" name="x" use="optional"/>
								<xs:attribute type="xs:int" name="y" use="optional"/>
								<xs:attribute type="xs:int" name="z" use="optional"/>
								<xs:attribute type="xs:int" name="heading" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sage-BR/L2JBr/dist/game/data/scripts/ai/areas/ImperialTomb/FourSepulchers/FourSepulchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FourSepulchers.xsd">
	<!-- SEPULCHER 1 - ROOM 1 -->
	<spawn sepulcherId="1" wave="1" npcId="18120" x="182214" y="-85572" z="-7219" heading="53601" /> <!-- key rewarder -->
	<spawn sepulcherId="1" wave="1" npcId="18132" x="181626" y="-85799" z="-7218" heading="48022" />
	<spawn sepulcherId="1" wave="1" npcId="18132" x="182223" y="-85833" z="-7220" heading="50241" />
	<spawn sepulcherId="1" wave="1" npcId="18132" x="181850" y="-85294" z="-7220" heading="20973" />
	<spawn sepulcherId="1" wave="1" npcId="18132" x="182260" y="-85353" z="-7218" heading="15208" />
	<spawn sepulcherId="1" wave="1" npcId="18133" x="181953" y="-85506" z="-7219" heading="38327" />
	<spawn sepulcherId="1" wave="1" npcId="18133" x="181639" y="-85397" z="-7218" heading="20774" />
	<spawn sepulcherId="1" wave="1" npcId="18133" x="182364" y="-86036" z="-7220" heading="664" />
	<spawn sepulcherId="1" wave="1" npcId="18133" x="182292" y="-85306" z="-7220" heading="11807" />
	<spawn sepulcherId="1" wave="1" npcId="18137" x="182499" y="-85379" z="-7218" heading="11039" />
	<spawn sepulcherId="1" wave="1" npcId="18137" x="181872" y="-85232" z="-7220" heading="12920" />
	<spawn sepulcherId="1" wave="1" npcId="18137" x="181933" y="-85500" z="-7216" heading="41059" />
	<spawn sepulcherId="1" wave="1" npcId="18137" x="181668" y="-85847" z="-7220" heading="41059" />
	<spawn sepulcherId="1" wave="1" npcId="18137" x="181921" y="-85909" z="-7216" heading="34037" />
	<spawn sepulcherId="1" wave="1" npcId="18137" x="182257" y="-85886" z="-7220" heading="39472" />
	<!-- SEPULCHER 1 - ROOM 2 -->
	<spawn sepulcherId="1" wave="2" npcId="18141" x="183799" y="-85246" z="-7217" heading="3307" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="184179" y="-85391" z="-7218" heading="51226" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="184153" y="-85262" z="-7220" heading="65064" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="184192" y="-85541" z="-7219" heading="50053" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="183812" y="-85901" z="-7220" heading="55728" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="184236" y="-85883" z="-7216" heading="442" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="183629" y="-85903" z="-7220" heading="26470" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="183631" y="-85653" z="-7219" heading="31350" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="183543" y="-85330" z="-7220" heading="9672" />
	<spawn sepulcherId="1" wave="2" npcId="18141" x="184213" y="-85694" z="-7219" heading="60977" />
	<!-- SEPULCHER 1 - ROOM 3 -->
	<spawn sepulcherId="1" wave="3" npcId="18150" x="185710" y="-85584" z="-7218" heading="833" /> <!-- victim -->
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185513" y="-85415" z="-7218" heading="29444" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185336" y="-85408" z="-7218" heading="22923" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185548" y="-85174" z="-7220" heading="4022" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185376" y="-85823" z="-7220" heading="18091" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185413" y="-86047" z="-7220" heading="33824" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185442" y="-85589" z="-7219" heading="13516" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185807" y="-85664" z="-7219" heading="64429" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185777" y="-86010" z="-7220" heading="42735" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185895" y="-85843" z="-7220" heading="53917" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185282" y="-85282" z="-7220" heading="27319" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="186031" y="-85572" z="-7219" heading="47324" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="186170" y="-85879" z="-7220" heading="53586" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="186220" y="-85157" z="-7220" heading="40777" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185858" y="-85220" z="-7220" heading="63999" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="186071" y="-85346" z="-7220" heading="59964" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="186050" y="-85970" z="-7220" heading="59476" />
	<spawn sepulcherId="1" wave="3" npcId="18166" x="185489" y="-85616" z="-7219" heading="44597" />
	<spawn sepulcherId="1" wave="3" npcId="18171" x="186220" y="-86036" z="-7220" heading="61673" />
	<spawn sepulcherId="1" wave="3" npcId="18171" x="185884" y="-85339" z="-7220" heading="3121" />
	<spawn sepulcherId="1" wave="3" npcId="18171" x="185696" y="-85397" z="-7218" heading="58467" />
	<spawn sepulcherId="1" wave="3" npcId="18171" x="185774" y="-85843" z="-7220" heading="26341" />
	<spawn sepulcherId="1" wave="3" npcId="18171" x="185524" y="-85895" z="-7219" heading="34907" />
	<spawn sepulcherId="1" wave="3" npcId="18171" x="185524" y="-85895" z="-7216" heading="22369" />
	<spawn sepulcherId="1" wave="3" npcId="18171" x="185450" y="-85199" z="-7219" heading="3565" />
	<spawn sepulcherId="1" wave="3" npcId="18171" x="185233" y="-85336" z="-7220" heading="20883" />
	<!-- SEPULCHER 1 - ROOM 4 -->
	<spawn sepulcherId="1" wave="4" npcId="18177" x="187536" y="-85561" z="-7219" heading="30267" /> <!-- key rewarder -->
	<spawn sepulcherId="1" wave="4" npcId="18196" x="186903" y="-85044" z="-7216" heading="55684" /> <!-- charm -->
	<spawn sepulcherId="1" wave="4" npcId="18197" x="188101" y="-85059" z="-7220" heading="38092" /> <!-- charm -->
	<spawn sepulcherId="1" wave="4" npcId="18198" x="188115" y="-86084" z="-7220" heading="24830" /> <!-- charm -->
	<spawn sepulcherId="1" wave="4" npcId="18199" x="186895" y="-86092" z="-7220" heading="9770" /> <!-- charm -->
	<spawn sepulcherId="1" wave="4" npcId="18185" x="187904" y="-85328" z="-7220" heading="8357" />
	<spawn sepulcherId="1" wave="4" npcId="18185" x="187696" y="-85307" z="-7220" heading="31718" />
	<spawn sepulcherId="1" wave="4" npcId="18185" x="187690" y="-85705" z="-7219" heading="14402" />
	<spawn sepulcherId="1" wave="4" npcId="18185" x="187428" y="-85743" z="-7219" heading="48912" />
	<spawn sepulcherId="1" wave="4" npcId="18185" x="187135" y="-85904" z="-7220" heading="38008" />
	<spawn sepulcherId="1" wave="4" npcId="18185" x="187235" y="-85292" z="-7220" heading="32428" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187955" y="-85906" z="-7220" heading="57628" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187907" y="-85704" z="-7219" heading="19115" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187645" y="-85421" z="-7219" heading="41743" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187774" y="-85271" z="-7216" heading="19492" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187419" y="-85213" z="-7220" heading="25008" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187144" y="-85228" z="-7220" heading="33336" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187066" y="-85410" z="-7218" heading="44928" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187575" y="-85835" z="-7220" heading="469" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187052" y="-85592" z="-7219" heading="48351" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187102" y="-85839" z="-7220" heading="51235" />
	<spawn sepulcherId="1" wave="4" npcId="18187" x="187245" y="-85956" z="-7220" heading="58383" />
	<!-- SEPULCHER 1 - ROOM 5 (First Wave) -->
	<spawn sepulcherId="1" wave="5" npcId="18232" x="189912" y="-86051" z="-7220" heading="32768" /> <!-- statue -->
	<spawn sepulcherId="1" wave="5" npcId="18232" x="189910" y="-85977" z="-7220" heading="32768" /> <!-- statue -->
	<spawn sepulcherId="1" wave="5" npcId="18232" x="189917" y="-85844" z="-7220" heading="32768" /> <!-- statue -->
	<spawn sepulcherId="1" wave="5" npcId="18232" x="189924" y="-85911" z="-7220" heading="32768" /> <!-- statue -->
	<spawn sepulcherId="1" wave="5" npcId="18232" x="189932" y="-85337" z="-7216" heading="32768" /> <!-- statue -->
	<spawn sepulcherId="1" wave="5" npcId="18232" x="189912" y="-85183" z="-7220" heading="32768" /> <!-- statue -->
	<spawn sepulcherId="1" wave="5" npcId="18232" x="189927" y="-85265" z="-7216" heading="32768" /> <!-- statue -->
	<spawn sepulcherId="1" wave="5" npcId="18232" x="189910" y="-85102" z="-7216" heading="32768" /> <!-- statue -->
	<spawn sepulcherId="1" wave="5" npcId="18220" x="189602" y="-85381" z="-7218" heading="16239" />
	<spawn sepulcherId="1" wave="5" npcId="18220" x="189433" y="-85782" z="-7218" heading="44991" />
	<spawn sepulcherId="1" wave="5" npcId="18220" x="189065" y="-85279" z="-7220" heading="14628" />
	<spawn sepulcherId="1" wave="5" npcId="18220" x="188986" y="-85744" z="-7218" heading="31883" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="189573" y="-85560" z="-7219" heading="53861" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="189444" y="-85294" z="-7220" heading="9381" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="189328" y="-85440" z="-7219" heading="59806" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="189065" y="-85279" z="-7220" heading="14628" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="189214" y="-85161" z="-7220" heading="3036" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="189002" y="-85428" z="-7219" heading="10979" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="188937" y="-85244" z="-7220" heading="19925" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="188880" y="-85642" z="-7219" heading="13008" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="188827" y="-85800" z="-7220" heading="18494" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="188859" y="-85956" z="-7220" heading="37418" />
	<spawn sepulcherId="1" wave="5" npcId="18222" x="189018" y="-85880" z="-7220" heading="43207" />
