=== Sage-BR/L2JBr/dist/game/data/xsd/buylist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="npcs" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
								<xs:simpleType>
									<xs:restriction base="xs:positiveInteger">
										<xs:minInclusive value="1" />
										<xs:maxInclusive value="65535" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<!--xs:maxInclusive value="65535" /-->
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="price" type="xs:nonNegativeInteger" />
						<xs:attribute name="restock_delay" type="xs:positiveInteger" />
						<xs:attribute name="count" type="xs:positiveInteger" />
						<xs:attribute name="baseTax" type="xs:positiveInteger" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="baseTax" type="xs:positiveInteger" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sage-BR/L2JBr/dist/game/data/buylists/0351864.xml
<?xml version="1.0" encoding="UTF-8"?>
<list baseTax="20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/buylist.xsd">
	<npcs>
		<npc>35186</npc> <!-- Arvid -->
	</npcs>
	<item id="6135" /> <!-- Dawn Mercenary Posting Ticket (Sword/Stationary) -->
	<item id="6136" /> <!-- Dawn Mercenary Posting Ticket (Spear/Stationary) -->
	<item id="6137" /> <!-- Dawn Mercenary Posting Ticket (Bow/Stationary) -->
	<item id="6138" /> <!-- Dawn Mercenary Posting Ticket (Cleric/Stationary) -->
	<item id="6139" /> <!-- Dawn Mercenary Posting Ticket (Wizard/Stationary) -->
	<item id="6140" /> <!-- Dawn Mercenary Posting Ticket (Sword/Mobile) -->
	<item id="6141" /> <!-- Dawn Mercenary Posting Ticket (Spear/Mobile) -->
	<item id="6142" /> <!-- Dawn Mercenary Posting Ticket (Bow/Mobile) -->
	<item id="6143" /> <!-- Dawn Mercenary Posting Ticket (Cleric/Mobile) -->
	<item id="6144" /> <!-- Dawn Mercenary Posting Ticket (Wizard/Mobile) -->
</list>

=== Sage-BR/L2JBr/dist/game/data/buylists/custom/0011097.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/buylist.xsd">
	<!-- (Paulinas) -->
	<item id="46881" price="0" />
	<item id="46882" price="0" />
	<item id="46883" price="0" />
	<item id="46884" price="0" />
	<item id="46885" price="0" />
	<item id="47038" price="0" />
	<item id="47039" price="0" />
	<item id="47040" price="0" />
	<item id="47041" price="0" />
	<item id="47042" price="0" />
	<item id="80052" price="0" />
	<item id="80053" price="0" />
	<item id="80054" price="0" />
	<item id="80055" price="0" />
	<item id="80056" price="0" />
	<item id="80057" price="0" />
	<item id="80320" price="0" />
</list>
