=== Sage-BR/L2JBr/dist/game/data/xsd/cubics.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="baseConditions">
		<xs:sequence>
			<xs:element name="hp" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:token">
								<xs:enumeration value="GREATER" />
								<xs:enumeration value="LESSER" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute type="xs:byte" name="percent" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="range" minOccurs="0">
				<xs:complexType>
					<xs:attribute type="xs:short" name="value" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="skillConditions">
		<xs:sequence>
			<xs:element name="hp" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:token">
								<xs:enumeration value="GREATER" />
								<xs:enumeration value="LESSER" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute type="xs:byte" name="percent" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="range" minOccurs="0">
				<xs:complexType>
					<xs:attribute type="xs:short" name="value" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="healthPercent" minOccurs="0">
				<xs:complexType>
					<xs:attribute type="xs:byte" name="min" use="required" />
					<xs:attribute type="xs:byte" name="max" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cubic" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="conditions" minOccurs="0" type="baseConditions" />
							<xs:element name="skills">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="conditions" minOccurs="0" type="skillConditions" />
												</xs:sequence>
												<xs:attribute type="xs:short" name="id" use="required" />
												<xs:attribute type="xs:byte" name="level" use="required" />
												<xs:attribute type="xs:positiveInteger" name="triggerRate" />
												<xs:attribute type="xs:positiveInteger" name="successRate" />
												<xs:attribute type="xs:boolean" name="canUseOnStaticObjects" />
												<xs:attribute name="target" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="HEAL" />
															<xs:enumeration value="MASTER" />
															<xs:enumeration value="TARGET" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute type="xs:boolean" name="targetDebuff" use="optional" />
												<xs:attribute type="xs:positiveInteger" name="range" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:byte" name="id" use="required" />
						<xs:attribute type="xs:byte" name="level" use="required" />
						<xs:attribute type="xs:byte" name="slot" use="required" />
						<xs:attribute type="xs:short" name="duration" use="required" />
						<xs:attribute type="xs:nonNegativeInteger" name="delay" use="required" />
						<xs:attribute type="xs:nonNegativeInteger" name="maxCount" use="required" />
						<xs:attribute type="xs:byte" name="useUp" use="required" />
						<xs:attribute type="xs:double" name="power" use="required" />
						<xs:attribute name="targetType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="BY_SKILL" />
									<xs:enumeration value="TARGET" />
									<xs:enumeration value="HEAL" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sage-BR/L2JBr/dist/game/data/stats/cubics/cubic-15.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/cubics.xsd">
	<cubic id="15" level="1" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="1" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="1" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="1" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="2" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="2" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="2" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="2" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="3" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="3" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="3" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="3" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="4" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="4" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="4" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="4" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="5" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="5" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="5" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="5" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="6" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="6" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="6" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="6" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="7" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="7" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="7" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="7" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="8" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="8" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="8" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="8" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="9" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="9" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="8" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="8" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="10" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="10" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="8" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="8" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
	<cubic id="15" level="11" slot="11" duration="900" delay="13" maxCount="50" useUp="0" power="2106.0" targetType="BY_SKILL">
		<skills>
			<skill id="11294" level="11" triggerRate="10" successRate="33" canUseOnStaticObjects="true" target="TARGET"> <!-- Cubic Root -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11293" level="8" triggerRate="10" successRate="45" target="TARGET"> <!-- Cubic Cancellation -->
				<conditions>
					<hp type="GREATER" percent="30" />
					<range value="1000" />
				</conditions>
			</skill>
			<skill id="11292" level="8" triggerRate="80" successRate="99" target="MASTER" targetDebuff="true" /> <!-- Cubic Cleanse -->
		</skills>
	</cubic>
</list>
