=== Sage-BR/L2JBr/dist/game/data/xsd/initialShortcuts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="shortcuts" minOccurs="1" maxOccurs="137">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="page" minOccurs="1" maxOccurs="4">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="slot" maxOccurs="12" minOccurs="1">
											<xs:complexType>
												<xs:attribute type="xs:byte" name="slotId" use="required" />
												<xs:attribute name="shortcutType" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="ITEM" />
															<xs:enumeration value="SKILL" />
															<xs:enumeration value="ACTION" />
															<xs:enumeration value="MACRO" />
															<xs:enumeration value="RECIPE" />
															<xs:enumeration value="BOOKMARK" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute type="xs:short" name="shortcutId" use="required" />
												<xs:attribute type="xs:byte" name="shortcutLevel" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="pageId" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:nonNegativeInteger">
												<xs:minInclusive value="0" />
												<xs:maxInclusive value="3" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="classId" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="189" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="macros" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="macro" maxOccurs="48">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="command" maxOccurs="12" minOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="type" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="SKILL" />
																	<xs:enumeration value="ACTION" />
																	<xs:enumeration value="TEXT" />
																	<xs:enumeration value="SHORTCUT" />
																	<xs:enumeration value="ITEM" />
																	<xs:enumeration value="DELAY" />
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute type="xs:positiveInteger" name="skillId" use="optional" />
														<xs:attribute type="xs:positiveInteger" name="skillLvl" use="optional" />
														<xs:attribute type="xs:nonNegativeInteger" name="page" use="optional" />
														<xs:attribute type="xs:nonNegativeInteger" name="slot" use="optional" />
														<xs:attribute type="xs:positiveInteger" name="actionId" use="optional" />
														<xs:attribute type="xs:positiveInteger" name="actionType" use="optional" />
														<xs:attribute type="xs:positiveInteger" name="itemId" use="optional" />
														<xs:attribute type="xs:positiveInteger" name="delay" use="optional" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:nonNegativeInteger" name="macroId" use="required" />
									<xs:attribute name="icon" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:byte">
												<xs:minInclusive value="0" />
												<xs:maxInclusive value="6" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute type="xs:string" name="name" use="required" />
									<xs:attribute type="xs:string" name="description" use="optional" />
									<xs:attribute type="xs:token" name="acronym" use="required" />
									<xs:attribute type="xs:boolean" name="enabled" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sage-BR/L2JBr/dist/game/data/stats/initialShortcuts.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/initialShortcuts.xsd">
	<!-- Global shortcuts -->
	<shortcuts>
		<page pageId="0">
			<slot slotId="0" shortcutType="ACTION" shortcutId="2" /> <!-- Attack -->
			<slot slotId="3" shortcutType="ACTION" shortcutId="5" /> <!-- Pick Up -->
			<slot slotId="4" shortcutType="ACTION" shortcutId="4" /> <!-- Next Target -->
			<slot slotId="10" shortcutType="ACTION" shortcutId="0" /> <!-- Sit/Stand -->
		</page>
		<!-- Custom example. -->
		<page pageId="1">
			<slot slotId="0" shortcutType="MACRO" shortcutId="10000" /> <!-- Macro Test -->
		</page>
	</shortcuts>
	<!-- Human Mystic -->
	<shortcuts classId="10">
		<page pageId="0">
			<slot slotId="1" shortcutType="SKILL" shortcutId="1177" shortcutLevel="1" /> <!-- Wind Strike -->
			<slot slotId="10" shortcutType="SKILL" shortcutId="1216" shortcutLevel="1" /> <!-- Self Heal -->
		</page>
	</shortcuts>
	<!-- Elven Mystic -->
	<shortcuts classId="25">
		<page pageId="0">
			<slot slotId="1" shortcutType="SKILL" shortcutId="1177" shortcutLevel="1" /> <!-- Wind Strike -->
			<slot slotId="10" shortcutType="SKILL" shortcutId="1216" shortcutLevel="1" /> <!-- Self Heal -->
		</page>
	</shortcuts>
	<!-- Dark Mystic -->
	<shortcuts classId="38">
		<page pageId="0">
			<slot slotId="1" shortcutType="SKILL" shortcutId="1177" shortcutLevel="1" /> <!-- Wind Strike -->
			<slot slotId="10" shortcutType="SKILL" shortcutId="1216" shortcutLevel="1" /> <!-- Self Heal -->
		</page>
	</shortcuts>
	<!-- Orc Mystic -->
	<shortcuts classId="49">
		<page pageId="0">
			<slot slotId="1" shortcutType="SKILL" shortcutId="1001" shortcutLevel="1" /> <!-- Soul Cry -->
		</page>
	</shortcuts>
	<!-- Ertheia Wizard -->
	<shortcuts classId="183">
		<page pageId="0">
			<slot slotId="1" shortcutType="SKILL" shortcutId="30001" shortcutLevel="1" /> <!-- Hydro Attack -->
		</page>
	</shortcuts>
	<!-- Macro presets -->
	<macros>
		<!-- Macro example with multiple commands. -->
		<macro macroId="10000" icon="1" name="Macro name" description="This is a test." acronym="HI!" enabled="false"> <!-- Macro ID must be over 1000, use higher values to avoid conflicts with already existing macros. -->
			<command type="SKILL" skillId="1177" skillLvl="1" /> <!-- To define a skill always include skill ID and level. -->
			<command type="DELAY" delay="5" /> <!-- To define a delay always define the time in seconds. -->
			<command type="TEXT">/loc</command> <!-- To define a command, just include the string as if it was typed in-game. -->
			<command type="TEXT">!Hellooooo world!</command> <!-- To define a text, just include the string as if it was typed in-game. -->
			<command type="SHORTCUT" page="0" slot="11" /> <!-- To define a shortcut (to an equipped item in example), include page and slot number. -->
		</macro>
	</macros>
</list>
