=== Sage-BR/L2JBr/dist/game/data/xsd/multisell.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="npcs" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
								<xs:simpleType>
									<xs:restriction base="xs:integer" />
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="ingredient" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:integer" use="required" />
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="enchantmentLevel" type="xs:integer" />
									<xs:attribute name="maintainIngredient" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="production" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:integer" use="required" />
									<xs:attribute name="enchantmentLevel" type="xs:integer" />
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="chance" type="xs:double" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="isChanceMultisell" type="xs:boolean" use="optional" />
			<xs:attribute name="applyTaxes" type="xs:boolean" />
			<xs:attribute name="maintainEnchantment" type="xs:boolean" />
			<xs:attribute name="ingredientMultiplier" type="xs:double" />
			<xs:attribute name="productMultiplier" type="xs:double" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sage-BR/L2JBr/dist/game/data/multisell/custom/600068.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/multisell.xsd">
	<npcs>
		<npc>-1</npc> <!-- CB -->
	</npcs>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80261" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80262" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80263" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80264" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80265" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80266" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80267" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80268" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80269" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80270" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80271" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80272" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80273" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80274" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80275" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80276" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80277" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80250" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80251" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80252" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80253" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80254" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80255" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80256" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80257" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80258" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80259" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80260" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80327" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80328" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="161659000" id="57" />
		<production count="1" id="80329" />
	</item>
</list>

=== Sage-BR/L2JBr/dist/game/data/multisell/3444503.xml
<?xml version="1.0" encoding="UTF-8"?>
<list isChanceMultisell="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>34445</npc> <!-- Accessory Artisan Denign -->
	</npcs>
	<item>
		<ingredient id="47214" count="1" /> <!-- Ring of Creation -->
		<ingredient id="47219" count="1" /> <!-- Source of the Emperor -->
		<production id="47215" count="1" chance="0" /> <!-- Ring of Authority -->
		<production id="47215" count="1" chance="5" /> <!-- Ring of Authority -->
		<production id="47214" count="1" chance="95" /> <!-- Ring of Creation -->
	</item>
	<item>
		<ingredient id="47214" count="1" /> <!-- Ring of Creation -->
		<ingredient id="47219" count="1" /> <!-- Source of the Emperor -->
		<production id="47217" count="1" chance="0" /> <!-- Ring of the Truth -->
		<production id="47217" count="1" chance="5" /> <!-- Ring of the Truth -->
		<production id="47214" count="1" chance="95" /> <!-- Ring of Creation -->
	</item>
	<item>
		<ingredient id="47217" count="1" /> <!-- Ring of the Truth -->
		<ingredient id="47219" count="1" /> <!-- Source of the Emperor -->
		<production id="47218" count="1" chance="0" /> <!-- Ring of the Truth-Seeker -->
		<production id="47218" count="1" chance="5" /> <!-- Ring of the Truth-Seeker -->
		<production id="47219" count="40" chance="95" /> <!-- Source of the Emperor -->
	</item>
	<item>
		<ingredient id="47215" count="1" /> <!-- Ring of Authority -->
		<ingredient id="47219" count="1" /> <!-- Source of the Emperor -->
		<production id="47216" count="1" chance="0" /> <!-- Ruler's Ring of Authority -->
		<production id="47216" count="1" chance="5" /> <!-- Ruler's Ring of Authority -->
		<production id="47219" count="40" chance="95" /> <!-- Source of the Emperor -->
	</item>
</list>

=== Sage-BR/L2JBr/dist/game/data/multisell/734.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>33946</npc> <!-- Adventure Guildsman -->
	</npcs>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18347" count="1" /> <!-- Talisman (R99-grade) - Critical Damage (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18351" count="1" /> <!-- Talisman (R99-grade) - Critical P. Def. (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18319" count="1" /> <!-- Talisman (R99-grade) - P. Atk. (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18323" count="1" /> <!-- Talisman (R99-grade) - P. Def. (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18327" count="1" /> <!-- Talisman (R99-grade) - M. Atk. (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18331" count="1" /> <!-- Talisman (R99-grade) - M. Def. (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18335" count="1" /> <!-- Talisman (R99-grade) - HP (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18339" count="1" /> <!-- Talisman (R99-grade) - MP (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18343" count="1" /> <!-- Talisman (R99-grade) - CP (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18352" count="1" /> <!-- Talisman (R-grade) - M. Critical (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18353" count="1" /> <!-- Talisman (R-grade) - P. Accuracy (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18354" count="1" /> <!-- Talisman (R-grade) - M. Accuracy (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18355" count="1" /> <!-- Talisman (R-grade) - Evasion (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18356" count="1" /> <!-- Talisman (R-grade) - M. Evasion (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18357" count="1" /> <!-- Talisman (R-grade) - P. Critical Rate (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="18358" count="1" /> <!-- Talisman (R-grade) - Critical Evasion (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="33768" count="1" /> <!-- Talisman (R-grade) - Damage Reflect Resistance (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="33470" count="1" /> <!-- Special Talisman - M. Def. (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="33471" count="1" /> <!-- Special Talisman - Ranged Attack Resistance (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="32247" count="1" /> <!-- Talisman (R-grade) - Remove Debuff (Active) -->
	</item>
	<item>
		<ingredient id="17746" count="20" /> <!-- Seal of Spirit -->
		<production id="34622" count="1" /> <!-- Talisman (R-grade) - Half-kill/Lethal Strike Resistance (Active) -->
	</item>
</list>
