=== Sage-BR/L2JBr/dist/game/data/xsd/optionsData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="option" maxOccurs="100" minOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="effects" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded" minOccurs="1">
										<xs:element name="effect" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:float" name="amount" minOccurs="0" maxOccurs="1" />
													<xs:element type="xs:string" name="mode" minOccurs="0" maxOccurs="1" />
													<xs:element type="xs:string" name="attribute" minOccurs="0" maxOccurs="1" />
													<xs:element type="xs:byte" name="magicType" minOccurs="0" maxOccurs="1" />
													<xs:element type="xs:string" name="stat" minOccurs="0" maxOccurs="1" />
													<xs:element type="xs:float" name="SHOCK" minOccurs="0" />
													<xs:element type="xs:float" name="HOLD" minOccurs="0" />
													<xs:element type="xs:float" name="BLEED" minOccurs="0" />
													<xs:element type="xs:float" name="PARALYZE" minOccurs="0" />
													<xs:element type="xs:float" name="DERANGEMENT" minOccurs="0" />
													<xs:element type="xs:float" name="SLEEP" minOccurs="0" />
													<xs:element type="xs:float" name="POISON" minOccurs="0" />
													<xs:element type="xs:float" name="KNOCKBACK" minOccurs="0" />
													<xs:element type="xs:float" name="KNOCKDOWN" minOccurs="0" />
													<xs:element type="xs:float" name="AIRBIND" minOccurs="0" />
													<xs:element type="xs:float" name="PULL" minOccurs="0" />
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="active_skill" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="passive_skill" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="attack_skill" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="chance" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:decimal">
												<xs:minInclusive value="1.0" />
												<xs:maxInclusive value="100.0" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="critical_skill" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="chance" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:decimal">
												<xs:minInclusive value="1.0" />
												<xs:maxInclusive value="100.0" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="magic_skill" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="65535" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="level" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="chance" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:decimal">
												<xs:minInclusive value="1.0" />
												<xs:maxInclusive value="100.0" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="65535" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute type="xs:token" name="name" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sage-BR/L2JBr/dist/game/data/stats/augmentation/options/33300-33399.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/optionsData.xsd">
	<option id="33337" name="dragon_shirt">
		<!-- Acquired XP/ SP +3%, P./ M. Def. +5%, Speed +7, Received P./ M. Critical Damage -5%. -->
		<!-- STR +3, DEX +3, CON +3, INT +3, WIT +3, MEN +3, LUC +3, CHA +3. -->
		<active_skill id="35188" level="1" />
		<active_skill id="35189" level="1" />
		<active_skill id="35190" level="1" />
		<passive_skill id="35182" level="1" />
		<passive_skill id="35185" level="1" />
	</option>
	<option id="33338" name="dragon_shirt">
		<!-- Acquired XP/ SP +3%, P./ M. Def. +5%, Speed +7, Received P./ M. Critical Damage -5%. -->
		<!-- STR +3, DEX +3, CON +4, INT +3, WIT +3, MEN +4, LUC +3, CHA +3. -->
		<active_skill id="35188" level="2" />
		<active_skill id="35189" level="2" />
		<active_skill id="35190" level="2" />
		<passive_skill id="35182" level="1" />
		<passive_skill id="35185" level="2" />
	</option>
	<option id="33339" name="dragon_shirt">
		<!-- Acquired XP/ SP +3%, P./ M. Def. +5%, Speed +7, Received P./ M. Critical Damage -5%. -->
		<!-- STR +3, DEX +3, CON +4, INT +3, WIT +3, MEN +4, LUC +4, CHA +3. -->
		<active_skill id="35188" level="3" />
		<active_skill id="35189" level="3" />
		<active_skill id="35190" level="3" />
		<passive_skill id="35182" level="1" />
		<passive_skill id="35185" level="3" />
	</option>
	<option id="33340" name="dragon_shirt">
		<!-- Acquired XP/ SP +3%, P./ M. Def. +5%, Speed +7, Received P./ M. Critical Damage -5%. -->
		<!-- STR +3, DEX +4, CON +4, INT +3, WIT +4, MEN +4, LUC +4, CHA +3. -->
		<active_skill id="35188" level="4" />
		<active_skill id="35189" level="4" />
		<active_skill id="35190" level="4" />
		<passive_skill id="35182" level="1" />
		<passive_skill id="35185" level="4" />
	</option>
	<option id="33341" name="dragon_shirt">
		<!-- Acquired XP/ SP +3%, P./ M. Def. +5%, Speed +7, Received P./ M. Critical Damage -5%. -->
		<!-- STR +4, DEX +4, CON +4, INT +4, WIT +4, MEN +4, LUC +4, CHA +3. -->
		<active_skill id="35188" level="5" />
		<active_skill id="35189" level="5" />
		<active_skill id="35190" level="5" />
		<passive_skill id="35182" level="1" />
		<passive_skill id="35185" level="5" />
	</option>
	<option id="33342" name="dragon_shirt">
		<!-- Acquired XP/ SP +3%, P./ M. Def. +5%, Speed +7, Received P./ M. Critical Damage -5%. -->
		<!-- STR +4, DEX +4, CON +4, INT +4, WIT +4, MEN +4, LUC +4, CHA +4. -->
		<active_skill id="35188" level="6" />
		<active_skill id="35189" level="6" />
		<active_skill id="35190" level="6" />
		<passive_skill id="35182" level="1" />
		<passive_skill id="35185" level="6" />
	</option>
	<option id="33343" name="dragon_leather_shirt">
		<!-- Acquired XP/ SP +6%, P./ M. Def. +10%, Speed +7, Received P./ M. Critical Damage -10%, Skill Cooldown -3%. -->
		<!-- STR +4, DEX +4, CON +4, INT +4, WIT +4, MEN +4, LUC +4, CHA +4. -->
		<active_skill id="35188" level="7" />
		<active_skill id="35189" level="7" />
		<active_skill id="35190" level="7" />
		<passive_skill id="35183" level="1" />
		<passive_skill id="35186" level="1" />
	</option>
	<option id="33344" name="dragon_leather_shirt">
		<!-- Acquired XP/ SP +6%, P./ M. Def. +10%, Speed +7, Received P./ M. Critical Damage -10%, Skill Cooldown -3%. -->
		<!-- STR +4, DEX +4, CON +4, INT +4, WIT +4, MEN +4, LUC +4, CHA +4. -->
		<active_skill id="35188" level="8" />
		<active_skill id="35189" level="8" />
		<active_skill id="35190" level="8" />
		<passive_skill id="35183" level="1" />
		<passive_skill id="35186" level="2" />
	</option>
	<option id="33345" name="dragon_leather_shirt">
		<!-- Acquired XP/ SP +6%, P./ M. Def. +10%, Speed +7, Received P./ M. Critical Damage -10%, Skill Cooldown -3%. -->
		<!-- STR +4, DEX +4, CON +5, INT +4, WIT +4, MEN +5, LUC +4, CHA +4. -->
		<active_skill id="35188" level="9" />
		<active_skill id="35189" level="9" />
		<active_skill id="35190" level="9" />
		<passive_skill id="35183" level="1" />
		<passive_skill id="35186" level="3" />
	</option>
	<option id="33346" name="dragon_leather_shirt">
		<!-- Acquired XP/ SP +6%, P./ M. Def. +10%, Speed +7, Received P./ M. Critical Damage -10%, Skill Cooldown -3%. -->
		<!-- STR +4, DEX +5, CON +5, INT +4, WIT +5, MEN +5, LUC +5, CHA +4. -->
		<active_skill id="35188" level="10" />
		<active_skill id="35189" level="10" />
		<active_skill id="35190" level="10" />
		<passive_skill id="35183" level="1" />
		<passive_skill id="35186" level="4" />
	</option>
	<option id="33347" name="dragon_leather_shirt">
		<!-- Acquired XP/ SP +6%, P./ M. Def. +10%, Speed +7, Received P./ M. Critical Damage -10%, Skill Cooldown -3%. -->
		<!-- STR +5, DEX +5, CON +5, INT +5, WIT +5, MEN +5, LUC +5, CHA +4. -->
		<active_skill id="35188" level="11" />
		<active_skill id="35189" level="11" />
		<active_skill id="35190" level="11" />
		<passive_skill id="35183" level="1" />
		<passive_skill id="35186" level="5" />
	</option>
	<option id="33348" name="dragon_leather_shirt">
		<!-- Acquired XP/ SP +6%, P./ M. Def. +10%, Speed +7, Received P./ M. Critical Damage -10%, Skill Cooldown -3%. -->
		<!-- STR +5, DEX +5, CON +5, INT +5, WIT +5, MEN +5, LUC +5, CHA +5. -->
		<active_skill id="35188" level="12" />
		<active_skill id="35189" level="12" />
		<active_skill id="35190" level="12" />
		<passive_skill id="35183" level="1" />
		<passive_skill id="35186" level="6" />
	</option>
	<option id="33349" name="dragon_rind_leather_shirt">
		<!-- Acquired XP/ SP +10%, P./ M. Def. +15%, Speed +7, Received P./ M. Critical Damage -15%, Skill Cooldown -3%. -->
		<!-- STR +5, DEX +5, CON +5, INT +5, WIT +5, MEN +5, LUC +5, CHA +5. -->
		<active_skill id="35188" level="13" />
		<active_skill id="35189" level="13" />
		<active_skill id="35190" level="13" />
		<passive_skill id="35184" level="1" />
		<passive_skill id="35187" level="1" />
	</option>
	<option id="33350" name="dragon_rind_leather_shirt">
		<!-- Acquired XP/ SP +10%, P./ M. Def. +15%, Speed +7, Received P./ M. Critical Damage -15%, Skill Cooldown -3%. -->
		<!-- STR +5, DEX +5, CON +6, INT +5, WIT +5, MEN +6, LUC +5, CHA +5. -->
		<active_skill id="35188" level="14" />
		<active_skill id="35189" level="14" />
		<active_skill id="35190" level="14" />
		<passive_skill id="35184" level="1" />
		<passive_skill id="35187" level="2" />
	</option>
	<option id="33351" name="dragon_rind_leather_shirt">
		<!-- Acquired XP/ SP +10%, P./ M. Def. +15%, Speed +7, Received P./ M. Critical Damage -15%, Skill Cooldown -3%. -->
		<!-- STR +5, DEX +5, CON +6, INT +5, WIT +5, MEN +6, LUC +6, CHA +5. -->
		<active_skill id="35188" level="15" />
		<active_skill id="35189" level="15" />
		<active_skill id="35190" level="15" />
		<passive_skill id="35184" level="1" />
		<passive_skill id="35187" level="3" />
	</option>
	<option id="33352" name="dragon_rind_leather_shirt">
		<!-- Acquired XP/ SP +10%, P./ M. Def. +15%, Speed +7, Received P./ M. Critical Damage -15%, Skill Cooldown -3%. -->
		<!-- STR +5, DEX +6, CON +6, INT +5, WIT +6, MEN +6, LUC +6, CHA +5. -->
		<active_skill id="35188" level="16" />
		<active_skill id="35189" level="16" />
		<active_skill id="35190" level="16" />
		<passive_skill id="35184" level="1" />
		<passive_skill id="35187" level="4" />
	</option>
	<option id="33353" name="dragon_rind_leather_shirt">
		<!-- Acquired XP/ SP +10%, P./ M. Def. +15%, Speed +7, Received P./ M. Critical Damage -15%, Skill Cooldown -3%. -->
		<!-- STR +6, DEX +6, CON +6, INT +6, WIT +6, MEN +6, LUC +6, CHA +5. -->
		<active_skill id="35188" level="17" />
		<active_skill id="35189" level="17" />
		<active_skill id="35190" level="17" />
		<passive_skill id="35184" level="1" />
		<passive_skill id="35187" level="5" />
	</option>
	<option id="33354" name="dragon_rind_leather_shirt">
		<!-- Acquired XP/ SP +10%, P./ M. Def. +15%, Speed +7, Received P./ M. Critical Damage -15%, Skill Cooldown -3%. -->
		<!-- STR +6, DEX +6, CON +6, INT +6, WIT +6, MEN +6, LUC +6, CHA +6. -->
		<active_skill id="35188" level="18" />
		<active_skill id="35189" level="18" />
		<active_skill id="35190" level="18" />
		<passive_skill id="35184" level="1" />
		<passive_skill id="35187" level="6" />
	</option>
</list>
