=== Sage-BR/L2JBr/dist/game/data/xsd/pcKarmaIncrease.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pcKarmaIncrease">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="increase" minOccurs="121" maxOccurs="121">
					<xs:complexType>
						<xs:attribute name="lvl" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="121" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="val" type="xs:decimal" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sage-BR/L2JBr/dist/game/data/stats/chars/pcKarmaIncrease.xml
<?xml version="1.0" encoding="UTF-8"?>
<pcKarmaIncrease xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/pcKarmaIncrease.xsd">
	<increase lvl="1" val="0.772184315" />
	<increase lvl="2" val="2.069377971" />
	<increase lvl="3" val="2.315085083" />
	<increase lvl="4" val="2.467800843" />
	<increase lvl="5" val="2.514219611" />
	<increase lvl="6" val="2.510075822" />
	<increase lvl="7" val="2.532083418" />
	<increase lvl="8" val="2.473028945" />
	<increase lvl="9" val="2.377178509" />
	<increase lvl="10" val="2.285526643" />
	<increase lvl="11" val="2.654635163" />
	<increase lvl="12" val="2.963434737" />
	<increase lvl="13" val="3.266100461" />
	<increase lvl="14" val="3.561112664" />
	<increase lvl="15" val="3.847320291" />
	<increase lvl="16" val="4.123878064" />
	<increase lvl="17" val="4.390194136" />
	<increase lvl="18" val="4.645886341" />
	<increase lvl="19" val="4.890745518" />
	<increase lvl="20" val="5.124704707" />
	<increase lvl="21" val="6.97914069" />
	<increase lvl="22" val="7.270620642" />
	<increase lvl="23" val="7.548951721" />
	<increase lvl="24" val="7.81438302" />
	<increase lvl="25" val="8.067235867" />
	<increase lvl="26" val="8.307889422" />
	<increase lvl="27" val="8.536768399" />
	<increase lvl="28" val="8.754332624" />
	<increase lvl="29" val="8.961068152" />
	<increase lvl="30" val="9.157479758" />
	<increase lvl="31" val="11.41901707" />
	<increase lvl="32" val="11.64989746" />
	<increase lvl="33" val="11.87007991" />
	<increase lvl="34" val="12.08015809" />
	<increase lvl="35" val="12.28072687" />
	<increase lvl="36" val="12.47237891" />
	<increase lvl="37" val="12.65570177" />
	<increase lvl="38" val="12.83127553" />
	<increase lvl="39" val="12.99967093" />
	<increase lvl="40" val="13.16144786" />
	<increase lvl="41" val="15.6563607" />
	<increase lvl="42" val="15.84513182" />
	<increase lvl="43" val="16.02782135" />
	<increase lvl="44" val="16.20501182" />
	<increase lvl="45" val="16.37727218" />
	<increase lvl="46" val="16.54515749" />
	<increase lvl="47" val="16.70920885" />
	<increase lvl="48" val="16.86995336" />
	<increase lvl="49" val="17.02790439" />
	<increase lvl="50" val="17.18356182" />
	<increase lvl="51" val="19.85792061" />
	<increase lvl="52" val="20.04235517" />
	<increase lvl="53" val="20.22556446" />
	<increase lvl="54" val="20.40806338" />
	<increase lvl="55" val="20.59035551" />
	<increase lvl="56" val="20.77293378" />
	<increase lvl="57" val="20.95628115" />
	<increase lvl="58" val="21.1408714" />
	<increase lvl="59" val="21.3271699" />
	<increase lvl="60" val="21.51563446" />
	<increase lvl="61" val="24.3895427" />
	<increase lvl="62" val="24.61486587" />
	<increase lvl="63" val="24.84389213" />
	<increase lvl="64" val="25.07711247" />
	<increase lvl="65" val="25.31501442" />
	<increase lvl="66" val="25.55808296" />
	<increase lvl="67" val="25.80680152" />
	<increase lvl="68" val="26.06165297" />
	<increase lvl="69" val="26.32312062" />
	<increase lvl="70" val="26.59168923" />
	<increase lvl="71" val="29.73700169" />
	<increase lvl="72" val="30.05608089" />
	<increase lvl="73" val="30.38439021" />
	<increase lvl="74" val="30.72248074" />
	<increase lvl="75" val="31.07091037" />
	<increase lvl="76" val="31.43024494" />
	<increase lvl="77" val="31.80105928" />
	<increase lvl="78" val="32.18393847" />
	<increase lvl="79" val="32.57947894" />
	<increase lvl="80" val="32.98828968" />
	<increase lvl="81" val="33.41099339" />
	<increase lvl="82" val="33.84822779" />
	<increase lvl="83" val="34.30064673" />
	<increase lvl="84" val="34.76892155" />
	<increase lvl="85" val="479.147712" />
	<increase lvl="86" val="485.0585125" />
	<increase lvl="87" val="491.721465" />
	<increase lvl="88" val="498.388594" />
	<increase lvl="89" val="505.0597795" />
	<increase lvl="90" val="511.7349135" />
	<increase lvl="91" val="518.413887" />
	<increase lvl="92" val="525.096596" />
	<increase lvl="93" val="531.782941" />
	<increase lvl="94" val="538.472825" />
	<increase lvl="95" val="545.1661555" />
	<increase lvl="96" val="551.8628415" />
	<increase lvl="97" val="558.5627975" />
	<increase lvl="98" val="565.2659385" />
	<increase lvl="99" val="571.9721845" />
	<increase lvl="100" val="578.6753255" /> <!-- TODO: custom, update me -->
	<increase lvl="101" val="585.3784665" /> <!-- TODO: custom, update me -->
	<increase lvl="102" val="592.0816075" /> <!-- TODO: custom, update me -->
	<increase lvl="103" val="598.7847485" /> <!-- TODO: custom, update me -->
	<increase lvl="104" val="605.4878895" /> <!-- TODO: custom, update me -->
	<increase lvl="105" val="612.1910305" /> <!-- TODO: custom, update me -->
	<increase lvl="106" val="618.8941715" /> <!-- TODO: custom, update me -->
	<increase lvl="107" val="625.5973125" /> <!-- TODO: custom, update me -->
	<increase lvl="108" val="632.3004535" /> <!-- TODO: custom, update me -->
	<increase lvl="109" val="639.0035945" /> <!-- TODO: custom, update me -->
	<increase lvl="110" val="645.7067355" /> <!-- TODO: custom, update me -->
	<increase lvl="111" val="652.4098765" /> <!-- TODO: custom, update me -->
	<increase lvl="112" val="659.1130175" /> <!-- TODO: custom, update me -->
	<increase lvl="113" val="665.8161585" /> <!-- TODO: custom, update me -->
	<increase lvl="114" val="672.5192995" /> <!-- TODO: custom, update me -->
	<increase lvl="115" val="679.2224405" /> <!-- TODO: custom, update me -->
	<increase lvl="116" val="685.9255815" /> <!-- TODO: custom, update me -->
	<increase lvl="117" val="692.6287225" /> <!-- TODO: custom, update me -->
	<increase lvl="118" val="699.3318635" /> <!-- TODO: custom, update me -->
	<increase lvl="119" val="706.0350045" /> <!-- TODO: custom, update me -->
	<increase lvl="120" val="712.7381455" /> <!-- TODO: custom, update me -->
	<increase lvl="121" val="719.4412865" /> <!-- TODO: custom, update me -->
</pcKarmaIncrease>
