=== Sage-BR/L2JBr/dist/game/data/xsd/teleporterData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="npcs" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="npc" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:int" name="id" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="teleport" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="location" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:string" name="name" use="optional" />
												<xs:attribute type="xs:int" name="npcStringId" use="optional" />
												<xs:attribute type="xs:int" name="x" use="required" />
												<xs:attribute type="xs:int" name="y" use="required" />
												<xs:attribute type="xs:short" name="z" use="required" />
												<xs:attribute type="xs:int" name="questZoneId" use="optional" />
												<xs:attribute type="xs:int" name="feeId" use="optional" />
												<xs:attribute type="xs:int" name="feeCount" use="optional" />
												<xs:attribute name="castleId" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:pattern value="\d+(;\d+)*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="optional" />
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="NORMAL" />
												<xs:enumeration value="HUNTING" />
												<xs:enumeration value="NOBLES_TOKEN" />
												<xs:enumeration value="NOBLES_ADENA" />
												<xs:enumeration value="OTHER" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:integer" name="id" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sage-BR/L2JBr/dist/game/data/teleporters/town/Astiel.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/teleporterData.xsd">
	<npc id="33948"> <!-- Astiel -->
		<teleport type="NORMAL">
			<location npcStringId="1010199" x="148015" y="-55293" z="-2733" feeCount="110000" /> <!-- Town of Goddard -->
			<location npcStringId="1010005" x="-14608" y="123920" z="-3128" questZoneId="20" feeCount="28000" /> <!-- The Town of Gludio -->
			<location npcStringId="1010007" x="83551" y="147945" z="-3395" feeCount="57000" /> <!-- The Town of Giran -->
			<location npcStringId="1010006" x="15487" y="142871" z="-2701" questZoneId="48" feeCount="42000" /> <!-- The Town of Dion -->
			<location npcStringId="1010200" x="43823" y="-47760" z="-796" feeCount="96000" /> <!-- Town of Rune -->
			<location npcStringId="1010049" x="111453" y="219391" z="-3545" questZoneId="118" feeCount="58000" /> <!-- Heine -->
			<location npcStringId="1010574" x="87130" y="-143514" z="-1291" feeCount="120000" /> <!-- Town of Schuttgart -->
			<location npcStringId="1010023" x="146798" y="25796" z="-2012" questZoneId="77" feeCount="95000" /> <!-- Town of Aden -->
			<location npcStringId="1010013" x="82958" y="53213" z="-1495" questZoneId="101" feeCount="76000" /> <!-- Town of Oren -->
			<location npcStringId="1010724" x="207482" y="86610" z="-1000" feeCount="99000" /> <!-- Ancient City Arcan -->
			<location npcStringId="1010004" x="-80684" y="149770" z="-3040" feeCount="23000" questZoneId="21" /> <!-- The Village of Gludin -->
			<location npcStringId="1010020" x="117070" y="76936" z="-2696" feeCount="78000" /> <!-- Hunter's Village -->
			<location npcStringId="1010001" x="-113443" y="256656" z="-1504" questZoneId="35" feeCount="2700" /> <!-- Talking Island Village -->
			<location npcStringId="1010155" x="44734" y="49210" z="-3056" feeCount="70000" /> <!-- Elven Village -->
			<location npcStringId="1010156" x="11167" y="16012" z="-4584" feeCount="74000" /> <!-- Dark Elf Village -->
			<location npcStringId="1010008" x="-44124" y="-113390" z="-240" feeCount="100000" /> <!-- Orc Village -->
			<location npcStringId="1010158" x="115357" y="-178212" z="-928" feeCount="140000" /> <!-- Dwarven Village -->
			<location npcStringId="1010648" x="-117001" y="46589" z="360" feeCount="61000" /> <!-- Kamael Village -->
		</teleport>
		<teleport type="HUNTING">
			<location npcStringId="1010742" x="-82399" y="244118" z="-3738" questZoneId="543" feeCount="810" /> <!-- Whispering Woods -->
		</teleport>
	</npc>
</list>
